// This file is generated by Slice Machine. Update with care!

import Features from './Features';
import Hero from './Hero';
import ImageAndText from './ImageAndText';

export {
	Features,
	Hero,
	ImageAndText,
};

export const components = {
	features: Features,
	hero: Hero,
	image_and_text: ImageAndText,
};
